name: firstworkflow
on: workflow_dispatch
jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello, World!"
      - name: print goodbye
        run: |
          echo "This is my first github workflow"
          echo "workflow executed successfully"